### ISSUE TITLE
Deleting a tag leads to crash

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#93] opened 2021-10-07 17:36 UTC
https://user-images.githubusercontent.com/581023/136435052-db42be87-1c86-4d6a-ac74-400fd4a0da16.mp4

```
D/gallery-screen: resource 2123566082 has tags [123]
    displaying tags of resource 2123566082 for preview
W/libEGL: EGLNativeWindowType 0x711d4e1010 disconnect failed
I/ViewRootImpl: jank_removeInvalidNode jank list is null
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
D/gallery-screen: tag 123 on resource 2123566082 long-clicked
D/gallery-screen: closing dialog in GalleryFragment
D/gallery-screen: displaying tags of resource 2123566082 for preview
D/gallery-screen: displaying tags resource 2123566082 for edit
D/AndroidRuntime: Shutting down VM
W/an.arknavigato: Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
E/an.arknavigato: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: space.taran.arknavigator, PID: 11758
    kotlin.UninitializedPropertyAccessException: lateinit property dialogBinding has not been initialized
        at space.taran.arknavigator.ui.fragments.GalleryFragment.displayDialogTags(GalleryFragment.kt:320)
        at space.taran.arknavigator.ui.fragments.GalleryFragment.replaceTags(GalleryFragment.kt:366)
        at space.taran.arknavigator.ui.fragments.GalleryFragment.removeTag(GalleryFragment.kt:359)
        at space.taran.arknavigator.ui.fragments.GalleryFragment.displayPreviewTags$lambda-11$lambda-10(GalleryFragment.kt:347)
        at space.taran.arknavigator.ui.fragments.GalleryFragment.lambda$pfmxukSI8qexTCGzEluvNyT3YDs(Unknown Source:0)
        at space.taran.arknavigator.ui.fragments.-$$Lambda$GalleryFragment$pfmxukSI8qexTCGzEluvNyT3YDs.onLongClick(Unknown Source:9)
        at android.view.View.performLongClickInternal(View.java:6747)
        at android.view.View.performLongClick(View.java:6705)
        at android.widget.TextView.performLongClick(TextView.java:11739)
        at android.view.View.performLongClick(View.java:6723)
        at android.view.View$CheckForLongPress.run(View.java:26150)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by kirillt** [comment] 2021-10-09 19:21
@melvin4u445 thanks, the device I've used when encountered this is Android 9. But I think it's irrelevant actually. Might be also some tricky conditions involved, but good that you've reproduced too.

**Comment by vedranqa** [comment] 2021-11-12 17:25
Can't reproduce these cases. 
Tested on Android 10

**Comment by melvin4u445** [comment] 2022-01-31 04:08
Cannot reproduce anymore. Closing this ticket

**Closed by melvin4u445** 2022-01-31 04:08 UTC
Labels: bug, needs verification
